[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["Hrum"]

[tool.poetry.dependencies]
python = "^3.8"
rstr = "^2.2.6"
aiofiles = "^0.5.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
